//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkassoMiddleware.Soap
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", ConfigurationName="InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap")]
    public interface IIcelandicOnlineBankingClaimsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CreateClaims", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CreateClaimsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.CreateClaimsResponse> CreateClaimsAsync(InkassoMiddleware.Soap.CreateClaimsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/AlterClaims", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/AlterClaimsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.AlterClaimsResponse> AlterClaimsAsync(InkassoMiddleware.Soap.AlterClaimsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CancelClaims", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CancelClaimsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.CancelClaimsResponse> CancelClaimsAsync(InkassoMiddleware.Soap.CancelClaimsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CreateClaim", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CreateClaimResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> CreateClaimAsync(InkassoMiddleware.Soap.Claim claim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/AlterClaim", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/AlterClaimResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> AlterClaimAsync(InkassoMiddleware.Soap.Claim claim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CancelClaim", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/CancelClaimResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> CancelClaimAsync(InkassoMiddleware.Soap.ClaimKey key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/GetClaimOperationResult", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/GetClaimOperationResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> GetClaimOperationResultAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/QueryClaims", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/QueryClaimsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.QueryClaimsResult> QueryClaimsAsync(InkassoMiddleware.Soap.ClaimsQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/QueryClaim", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/QueryClaimResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimInfo> QueryClaimAsync(InkassoMiddleware.Soap.ClaimKey key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/QueryPayments", ReplyAction="http://IcelandicOnlineBanking/2005/12/01/Claims/IIcelandicOnlineBankingClaimsSoap" +
            "/QueryPaymentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.QueryPaymentsResult> QueryPaymentsAsync(InkassoMiddleware.Soap.PaymentsQuery query);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClaimInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class Claim
    {
        
        private ClaimKey keyField;
        
        private string payorIDField;
        
        private System.DateTime cancellationDateField;
        
        private string identifierField;
        
        private decimal amountField;
        
        private string referenceField;
        
        private System.DateTime finalDueDateField;
        
        private string billNumberField;
        
        private string customerNumberField;
        
        private NoticeAndPaymentFee noticeAndPaymentFeeField;
        
        private DateRestrictedCharge defaultChargeField;
        
        private decimal otherCostsField;
        
        private decimal otherDefaultCostsField;
        
        private DefaultInterest defaultInterestField;
        
        private CurrencyInformation currencyInformationField;
        
        private bool permitOutOfSequencePaymentField;
        
        private DiscountCharge discountField;
        
        private bool isPartialPaymentAllowedField;
        
        private BillPresentmentSystem billPresentmentSystemField;
        
        private Printing printingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaimKey Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PayorID
        {
            get
            {
                return this.payorIDField;
            }
            set
            {
                this.payorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime CancellationDate
        {
            get
            {
                return this.cancellationDateField;
            }
            set
            {
                this.cancellationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime FinalDueDate
        {
            get
            {
                return this.finalDueDateField;
            }
            set
            {
                this.finalDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BillNumber
        {
            get
            {
                return this.billNumberField;
            }
            set
            {
                this.billNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public NoticeAndPaymentFee NoticeAndPaymentFee
        {
            get
            {
                return this.noticeAndPaymentFeeField;
            }
            set
            {
                this.noticeAndPaymentFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public DateRestrictedCharge DefaultCharge
        {
            get
            {
                return this.defaultChargeField;
            }
            set
            {
                this.defaultChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal OtherCosts
        {
            get
            {
                return this.otherCostsField;
            }
            set
            {
                this.otherCostsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal OtherDefaultCosts
        {
            get
            {
                return this.otherDefaultCostsField;
            }
            set
            {
                this.otherDefaultCostsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public DefaultInterest DefaultInterest
        {
            get
            {
                return this.defaultInterestField;
            }
            set
            {
                this.defaultInterestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public CurrencyInformation CurrencyInformation
        {
            get
            {
                return this.currencyInformationField;
            }
            set
            {
                this.currencyInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool PermitOutOfSequencePayment
        {
            get
            {
                return this.permitOutOfSequencePaymentField;
            }
            set
            {
                this.permitOutOfSequencePaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public DiscountCharge Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsPartialPaymentAllowed
        {
            get
            {
                return this.isPartialPaymentAllowedField;
            }
            set
            {
                this.isPartialPaymentAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public BillPresentmentSystem BillPresentmentSystem
        {
            get
            {
                return this.billPresentmentSystemField;
            }
            set
            {
                this.billPresentmentSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public Printing Printing
        {
            get
            {
                return this.printingField;
            }
            set
            {
                this.printingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimKey
    {
        
        private string claimantIDField;
        
        private string accountField;
        
        private System.DateTime dueDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClaimantID
        {
            get
            {
                return this.claimantIDField;
            }
            set
            {
                this.claimantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime DueDate
        {
            get
            {
                return this.dueDateField;
            }
            set
            {
                this.dueDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class CurrencyExchangeRate
    {
        
        private string currencyField;
        
        private decimal rateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class Payment
    {
        
        private ClaimKey keyField;
        
        private string payorIDField;
        
        private decimal amountField;
        
        private System.DateTime finalDueDateField;
        
        private string identifierField;
        
        private string referenceField;
        
        private string categoryCodeField;
        
        private string redeemingBankField;
        
        private System.DateTime transactionDateField;
        
        private System.DateTime bookingDateField;
        
        private System.DateTime valueDateField;
        
        private PaymentPaymentType paymentTypeField;
        
        private decimal amountDepositedField;
        
        private decimal totalAmountField;
        
        private decimal capitalGainsTaxField;
        
        private string billNumberField;
        
        private string customerNumberField;
        
        private decimal noticeChargeAmountField;
        
        private decimal defaultChargeAmountField;
        
        private decimal otherCostsAmountField;
        
        private decimal otherDefaultCostsAmountField;
        
        private decimal defaultInterestAmountField;
        
        private decimal discountAmountField;
        
        private CurrencyExchangeRate currencyField;
        
        private string batchNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaimKey Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PayorID
        {
            get
            {
                return this.payorIDField;
            }
            set
            {
                this.payorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime FinalDueDate
        {
            get
            {
                return this.finalDueDateField;
            }
            set
            {
                this.finalDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CategoryCode
        {
            get
            {
                return this.categoryCodeField;
            }
            set
            {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RedeemingBank
        {
            get
            {
                return this.redeemingBankField;
            }
            set
            {
                this.redeemingBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime BookingDate
        {
            get
            {
                return this.bookingDateField;
            }
            set
            {
                this.bookingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime ValueDate
        {
            get
            {
                return this.valueDateField;
            }
            set
            {
                this.valueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public PaymentPaymentType PaymentType
        {
            get
            {
                return this.paymentTypeField;
            }
            set
            {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal AmountDeposited
        {
            get
            {
                return this.amountDepositedField;
            }
            set
            {
                this.amountDepositedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal CapitalGainsTax
        {
            get
            {
                return this.capitalGainsTaxField;
            }
            set
            {
                this.capitalGainsTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BillNumber
        {
            get
            {
                return this.billNumberField;
            }
            set
            {
                this.billNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal NoticeChargeAmount
        {
            get
            {
                return this.noticeChargeAmountField;
            }
            set
            {
                this.noticeChargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal DefaultChargeAmount
        {
            get
            {
                return this.defaultChargeAmountField;
            }
            set
            {
                this.defaultChargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal OtherCostsAmount
        {
            get
            {
                return this.otherCostsAmountField;
            }
            set
            {
                this.otherCostsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal OtherDefaultCostsAmount
        {
            get
            {
                return this.otherDefaultCostsAmountField;
            }
            set
            {
                this.otherDefaultCostsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal DefaultInterestAmount
        {
            get
            {
                return this.defaultInterestAmountField;
            }
            set
            {
                this.defaultInterestAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal DiscountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public CurrencyExchangeRate Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BatchNumber
        {
            get
            {
                return this.batchNumberField;
            }
            set
            {
                this.batchNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum PaymentPaymentType
    {
        
        /// <remarks/>
        Complete,
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Refund,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class QueryPaymentsResult
    {
        
        private uint totalCountField;
        
        private Payment[] paymentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public uint TotalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Payments", Order=1)]
        public Payment[] Payments
        {
            get
            {
                return this.paymentsField;
            }
            set
            {
                this.paymentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class PaymentsQuery
    {
        
        private string claimantField;
        
        private string identifierField;
        
        private string disposalAccountField;
        
        private System.DateTime transactionDateFromField;
        
        private System.DateTime transactionDateToField;
        
        private uint entryFromField;
        
        private bool entryFromFieldSpecified;
        
        private uint entryToField;
        
        private bool entryToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Claimant
        {
            get
            {
                return this.claimantField;
            }
            set
            {
                this.claimantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DisposalAccount
        {
            get
            {
                return this.disposalAccountField;
            }
            set
            {
                this.disposalAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime TransactionDateFrom
        {
            get
            {
                return this.transactionDateFromField;
            }
            set
            {
                this.transactionDateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime TransactionDateTo
        {
            get
            {
                return this.transactionDateToField;
            }
            set
            {
                this.transactionDateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public uint EntryFrom
        {
            get
            {
                return this.entryFromField;
            }
            set
            {
                this.entryFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntryFromSpecified
        {
            get
            {
                return this.entryFromFieldSpecified;
            }
            set
            {
                this.entryFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public uint EntryTo
        {
            get
            {
                return this.entryToField;
            }
            set
            {
                this.entryToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntryToSpecified
        {
            get
            {
                return this.entryToFieldSpecified;
            }
            set
            {
                this.entryToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class QueryClaimsResult
    {
        
        private uint totalCountField;
        
        private ClaimInfo[] claimsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public uint TotalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Claims", Order=1)]
        public ClaimInfo[] Claims
        {
            get
            {
                return this.claimsField;
            }
            set
            {
                this.claimsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimInfo : Claim
    {
        
        private ClaimStatus statusField;
        
        private string categoryCodeField;
        
        private decimal totalAmountDueField;
        
        private decimal noticeChargeAmountField;
        
        private bool noticeChargeAmountFieldSpecified;
        
        private decimal defaultChargeAmountField;
        
        private bool defaultChargeAmountFieldSpecified;
        
        private decimal otherCostsAmountField;
        
        private bool otherCostsAmountFieldSpecified;
        
        private decimal otherDefaultCostsAmountField;
        
        private bool otherDefaultCostsAmountFieldSpecified;
        
        private decimal defaultInterestAmountField;
        
        private bool defaultInterestAmountFieldSpecified;
        
        private decimal discountAmountField;
        
        private bool discountAmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaimStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CategoryCode
        {
            get
            {
                return this.categoryCodeField;
            }
            set
            {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TotalAmountDue
        {
            get
            {
                return this.totalAmountDueField;
            }
            set
            {
                this.totalAmountDueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal NoticeChargeAmount
        {
            get
            {
                return this.noticeChargeAmountField;
            }
            set
            {
                this.noticeChargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoticeChargeAmountSpecified
        {
            get
            {
                return this.noticeChargeAmountFieldSpecified;
            }
            set
            {
                this.noticeChargeAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal DefaultChargeAmount
        {
            get
            {
                return this.defaultChargeAmountField;
            }
            set
            {
                this.defaultChargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultChargeAmountSpecified
        {
            get
            {
                return this.defaultChargeAmountFieldSpecified;
            }
            set
            {
                this.defaultChargeAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal OtherCostsAmount
        {
            get
            {
                return this.otherCostsAmountField;
            }
            set
            {
                this.otherCostsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherCostsAmountSpecified
        {
            get
            {
                return this.otherCostsAmountFieldSpecified;
            }
            set
            {
                this.otherCostsAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal OtherDefaultCostsAmount
        {
            get
            {
                return this.otherDefaultCostsAmountField;
            }
            set
            {
                this.otherDefaultCostsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherDefaultCostsAmountSpecified
        {
            get
            {
                return this.otherDefaultCostsAmountFieldSpecified;
            }
            set
            {
                this.otherDefaultCostsAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal DefaultInterestAmount
        {
            get
            {
                return this.defaultInterestAmountField;
            }
            set
            {
                this.defaultInterestAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultInterestAmountSpecified
        {
            get
            {
                return this.defaultInterestAmountFieldSpecified;
            }
            set
            {
                this.defaultInterestAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal DiscountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountAmountSpecified
        {
            get
            {
                return this.discountAmountFieldSpecified;
            }
            set
            {
                this.discountAmountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum ClaimStatus
    {
        
        /// <remarks/>
        Unpaid,
        
        /// <remarks/>
        Paid,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        SecondaryCollection,
        
        /// <remarks/>
        LegalCollection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimsQueryDateSpan
    {
        
        private System.DateTime dateFromField;
        
        private bool dateFromFieldSpecified;
        
        private System.DateTime dateToField;
        
        private bool dateToFieldSpecified;
        
        private DateSpanReferenceDate dateSpanReferenceDateField;
        
        private bool dateSpanReferenceDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateFromSpecified
        {
            get
            {
                return this.dateFromFieldSpecified;
            }
            set
            {
                this.dateFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateToSpecified
        {
            get
            {
                return this.dateToFieldSpecified;
            }
            set
            {
                this.dateToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateSpanReferenceDate DateSpanReferenceDate
        {
            get
            {
                return this.dateSpanReferenceDateField;
            }
            set
            {
                this.dateSpanReferenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpanReferenceDateSpecified
        {
            get
            {
                return this.dateSpanReferenceDateFieldSpecified;
            }
            set
            {
                this.dateSpanReferenceDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum DateSpanReferenceDate
    {
        
        /// <remarks/>
        DueDate,
        
        /// <remarks/>
        FinalDueDate,
        
        /// <remarks/>
        CancellationDate,
        
        /// <remarks/>
        CreationDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimsQuery
    {
        
        private string claimantField;
        
        private string identifierField;
        
        private ClaimsQueryDateSpan periodField;
        
        private string payorField;
        
        private ClaimStatus statusField;
        
        private bool statusFieldSpecified;
        
        private uint entryFromField;
        
        private bool entryFromFieldSpecified;
        
        private uint entryToField;
        
        private bool entryToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Claimant
        {
            get
            {
                return this.claimantField;
            }
            set
            {
                this.claimantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ClaimsQueryDateSpan Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Payor
        {
            get
            {
                return this.payorField;
            }
            set
            {
                this.payorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ClaimStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public uint EntryFrom
        {
            get
            {
                return this.entryFromField;
            }
            set
            {
                this.entryFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntryFromSpecified
        {
            get
            {
                return this.entryFromFieldSpecified;
            }
            set
            {
                this.entryFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public uint EntryTo
        {
            get
            {
                return this.entryToField;
            }
            set
            {
                this.entryToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntryToSpecified
        {
            get
            {
                return this.entryToFieldSpecified;
            }
            set
            {
                this.entryToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/CommonTypes")]
    public partial class Error
    {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimError
    {
        
        private ClaimKey keyField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaimKey Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Error Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimResult
    {
        
        private ClaimKey keyField;
        
        private PrintInformation printField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaimKey Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PrintInformation Print
        {
            get
            {
                return this.printField;
            }
            set
            {
                this.printField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum PrintInformation
    {
        
        /// <remarks/>
        NoInformation,
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        DirectPaymentClaim,
        
        /// <remarks/>
        InternetBankingClaim,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ClaimOperationResult
    {
        
        private string idField;
        
        private BatchStatus statusField;
        
        private ClaimResult[] successField;
        
        private ClaimError[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BatchStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Success", Order=2)]
        public ClaimResult[] Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Order=3)]
        public ClaimError[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum BatchStatus
    {
        
        /// <remarks/>
        InProgress,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        CompletedWithErrors,
        
        /// <remarks/>
        NotConfirmed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class ItemRow
    {
        
        private string textField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/CommonTypes")]
    public partial class Address
    {
        
        private string nameField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string postCodeNumberField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostCodeNumber
        {
            get
            {
                return this.postCodeNumberField;
            }
            set
            {
                this.postCodeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class Printing
    {
        
        private Address claimantAddressField;
        
        private Address payorAddressField;
        
        private ItemRow[] itemRowsField;
        
        private string[] commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address ClaimantAddress
        {
            get
            {
                return this.claimantAddressField;
            }
            set
            {
                this.claimantAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address PayorAddress
        {
            get
            {
                return this.payorAddressField;
            }
            set
            {
                this.payorAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemRows", Order=2)]
        public ItemRow[] ItemRows
        {
            get
            {
                return this.itemRowsField;
            }
            set
            {
                this.itemRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments", Order=3)]
        public string[] Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class BillPresentmentSystem
    {
        
        private string typeField;
        
        private string parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class CurrencyInformation
    {
        
        private CurrencyInformationReferenceRate referenceRateField;
        
        private string currencyField;
        
        private CurrencyInformationPaymentRate paymentRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CurrencyInformationReferenceRate ReferenceRate
        {
            get
            {
                return this.referenceRateField;
            }
            set
            {
                this.referenceRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CurrencyInformationPaymentRate PaymentRate
        {
            get
            {
                return this.paymentRateField;
            }
            set
            {
                this.paymentRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum CurrencyInformationReferenceRate
    {
        
        /// <remarks/>
        ExchangeRate,
        
        /// <remarks/>
        NoteRate,
        
        /// <remarks/>
        CentralBankMidRate,
        
        /// <remarks/>
        CentralBankStatutoryRate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum CurrencyInformationPaymentRate
    {
        
        /// <remarks/>
        DueDateRate,
        
        /// <remarks/>
        PaymentDateRate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class DefaultInterest
    {
        
        private DefaultInterestRule ruleField;
        
        private decimal percentage4Field;
        
        private bool percentage4FieldSpecified;
        
        private string specialCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DefaultInterestRule Rule
        {
            get
            {
                return this.ruleField;
            }
            set
            {
                this.ruleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Percentage4
        {
            get
            {
                return this.percentage4Field;
            }
            set
            {
                this.percentage4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Percentage4Specified
        {
            get
            {
                return this.percentage4FieldSpecified;
            }
            set
            {
                this.percentage4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SpecialCode
        {
            get
            {
                return this.specialCodeField;
            }
            set
            {
                this.specialCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum DefaultInterestRule
    {
        
        /// <remarks/>
        NoDefaultInterest,
        
        /// <remarks/>
        DefaultInterestAmount,
        
        /// <remarks/>
        DefaultInterestAmountAndDefaultCharge,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscountOrDefaultChargeAmount))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscountOrDefaultChargePercentage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public abstract partial class DiscountOrDefaultChargeBase
    {
        
        private int daysField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Days
        {
            get
            {
                return this.daysField;
            }
            set
            {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class DiscountOrDefaultChargeAmount : DiscountOrDefaultChargeBase
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class DiscountOrDefaultChargePercentage : DiscountOrDefaultChargeBase
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscountCharge))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class DateRestrictedCharge
    {
        
        private DiscountOrDefaultChargeBase firstField;
        
        private DiscountOrDefaultChargeBase secondField;
        
        private ReferenceDate referenceDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DiscountOrDefaultChargeBase First
        {
            get
            {
                return this.firstField;
            }
            set
            {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DiscountOrDefaultChargeBase Second
        {
            get
            {
                return this.secondField;
            }
            set
            {
                this.secondField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReferenceDate ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public enum ReferenceDate
    {
        
        /// <remarks/>
        DueDate,
        
        /// <remarks/>
        FinalDueDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class DiscountCharge : DateRestrictedCharge
    {
        
        private bool isPostRefDateField;
        
        public DiscountCharge()
        {
            this.isPostRefDateField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsPostRefDate
        {
            get
            {
                return this.isPostRefDateField;
            }
            set
            {
                this.isPostRefDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
    public partial class NoticeAndPaymentFee
    {
        
        private decimal printingField;
        
        private decimal paperlessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Printing
        {
            get
            {
                return this.printingField;
            }
            set
            {
                this.printingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Paperless
        {
            get
            {
                return this.paperlessField;
            }
            set
            {
                this.paperlessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateClaims", WrapperNamespace="http://IcelandicOnlineBanking/2005/12/01/Claims", IsWrapped=true)]
    public partial class CreateClaimsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
        public InkassoMiddleware.Soap.Claim[] claims;
        
        public CreateClaimsRequest()
        {
        }
        
        public CreateClaimsRequest(InkassoMiddleware.Soap.Claim[] claims)
        {
            this.claims = claims;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateClaimsResponse", WrapperNamespace="http://IcelandicOnlineBanking/2005/12/01/Claims", IsWrapped=true)]
    public partial class CreateClaimsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", Order=0)]
        public string CreateClaimsResult;
        
        public CreateClaimsResponse()
        {
        }
        
        public CreateClaimsResponse(string CreateClaimsResult)
        {
            this.CreateClaimsResult = CreateClaimsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlterClaims", WrapperNamespace="http://IcelandicOnlineBanking/2005/12/01/Claims", IsWrapped=true)]
    public partial class AlterClaimsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
        public InkassoMiddleware.Soap.Claim[] claims;
        
        public AlterClaimsRequest()
        {
        }
        
        public AlterClaimsRequest(InkassoMiddleware.Soap.Claim[] claims)
        {
            this.claims = claims;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlterClaimsResponse", WrapperNamespace="http://IcelandicOnlineBanking/2005/12/01/Claims", IsWrapped=true)]
    public partial class AlterClaimsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", Order=0)]
        public string AlterClaimsResult;
        
        public AlterClaimsResponse()
        {
        }
        
        public AlterClaimsResponse(string AlterClaimsResult)
        {
            this.AlterClaimsResult = AlterClaimsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelClaims", WrapperNamespace="http://IcelandicOnlineBanking/2005/12/01/Claims", IsWrapped=true)]
    public partial class CancelClaimsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/ClaimTypes")]
        public InkassoMiddleware.Soap.ClaimKey[] keys;
        
        public CancelClaimsRequest()
        {
        }
        
        public CancelClaimsRequest(InkassoMiddleware.Soap.ClaimKey[] keys)
        {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelClaimsResponse", WrapperNamespace="http://IcelandicOnlineBanking/2005/12/01/Claims", IsWrapped=true)]
    public partial class CancelClaimsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/Claims", Order=0)]
        public string CancelClaimsResult;
        
        public CancelClaimsResponse()
        {
        }
        
        public CancelClaimsResponse(string CancelClaimsResult)
        {
            this.CancelClaimsResult = CancelClaimsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IIcelandicOnlineBankingClaimsSoapChannel : InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class IcelandicOnlineBankingClaimsSoapClient : System.ServiceModel.ClientBase<InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap>, InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IcelandicOnlineBankingClaimsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(IcelandicOnlineBankingClaimsSoapClient.GetBindingForEndpoint(endpointConfiguration), IcelandicOnlineBankingClaimsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IcelandicOnlineBankingClaimsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IcelandicOnlineBankingClaimsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IcelandicOnlineBankingClaimsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IcelandicOnlineBankingClaimsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IcelandicOnlineBankingClaimsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.CreateClaimsResponse> InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap.CreateClaimsAsync(InkassoMiddleware.Soap.CreateClaimsRequest request)
        {
            return base.Channel.CreateClaimsAsync(request);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.CreateClaimsResponse> CreateClaimsAsync(InkassoMiddleware.Soap.Claim[] claims)
        {
            InkassoMiddleware.Soap.CreateClaimsRequest inValue = new InkassoMiddleware.Soap.CreateClaimsRequest();
            inValue.claims = claims;
            return ((InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap)(this)).CreateClaimsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.AlterClaimsResponse> InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap.AlterClaimsAsync(InkassoMiddleware.Soap.AlterClaimsRequest request)
        {
            return base.Channel.AlterClaimsAsync(request);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.AlterClaimsResponse> AlterClaimsAsync(InkassoMiddleware.Soap.Claim[] claims)
        {
            InkassoMiddleware.Soap.AlterClaimsRequest inValue = new InkassoMiddleware.Soap.AlterClaimsRequest();
            inValue.claims = claims;
            return ((InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap)(this)).AlterClaimsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InkassoMiddleware.Soap.CancelClaimsResponse> InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap.CancelClaimsAsync(InkassoMiddleware.Soap.CancelClaimsRequest request)
        {
            return base.Channel.CancelClaimsAsync(request);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.CancelClaimsResponse> CancelClaimsAsync(InkassoMiddleware.Soap.ClaimKey[] keys)
        {
            InkassoMiddleware.Soap.CancelClaimsRequest inValue = new InkassoMiddleware.Soap.CancelClaimsRequest();
            inValue.keys = keys;
            return ((InkassoMiddleware.Soap.IIcelandicOnlineBankingClaimsSoap)(this)).CancelClaimsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> CreateClaimAsync(InkassoMiddleware.Soap.Claim claim)
        {
            return base.Channel.CreateClaimAsync(claim);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> AlterClaimAsync(InkassoMiddleware.Soap.Claim claim)
        {
            return base.Channel.AlterClaimAsync(claim);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> CancelClaimAsync(InkassoMiddleware.Soap.ClaimKey key)
        {
            return base.Channel.CancelClaimAsync(key);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimOperationResult> GetClaimOperationResultAsync(string id)
        {
            return base.Channel.GetClaimOperationResultAsync(id);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.QueryClaimsResult> QueryClaimsAsync(InkassoMiddleware.Soap.ClaimsQuery query)
        {
            return base.Channel.QueryClaimsAsync(query);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.ClaimInfo> QueryClaimAsync(InkassoMiddleware.Soap.ClaimKey key)
        {
            return base.Channel.QueryClaimAsync(key);
        }
        
        public System.Threading.Tasks.Task<InkassoMiddleware.Soap.QueryPaymentsResult> QueryPaymentsAsync(InkassoMiddleware.Soap.PaymentsQuery query)
        {
            return base.Channel.QueryPaymentsAsync(query);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MS))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.TransportWithMessageCredential;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                result.Security.Message.ClientCredentialType = System.ServiceModel.MessageCredentialType.UserName;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MSNSC))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.TransportWithMessageCredential;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                result.Security.Message.ClientCredentialType = System.ServiceModel.MessageCredentialType.UserName;
                result.Security.Message.EstablishSecurityContext = false;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MS))
            {
                return new System.ServiceModel.EndpointAddress("https://demo-inkasso.azurewebsites.net/SOAP/IOBS/IcelandicOnlineBankingClaimsSoap" +
                        ".svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.MSNSC))
            {
                return new System.ServiceModel.EndpointAddress("https://demo-inkasso.azurewebsites.net/SOAP/IOBS/IcelandicOnlineBankingClaimsSoap" +
                        ".svc/NoSc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MS,
            
            MSNSC,
        }
    }
}
